---
- hosts: webservers
  become: yes
  vars:
   - Mymessage: "Welcome to webservers"
  
  tasks:
   - name: ensure to install nginx is at the latest version 
     apt: name=nginx state=latest
   - name: ensure list of php packages are at the latest version
     apt: name={{ item }} state=latest
     with_items:
        - php
        - php-fpm
- hosts: haproxy
  become: yes
  vars:
   - Mymessage: "Welcome to haproxy loadbalancer"
  
  tasks:
   - name: ensure to install haproxy is at the latest version
     apt: name=haproxy state=latest
