---
- hosts: webservers
  become: yes
  vars:
    - Mymessage: "Welcome to webservers"
  
  tasks:
    - name: ensure to install nginx is at the latest version 
      apt: name=nginx state=latest update_cache=yes
    
    - name: ensure to nginx start
      service:
        name: nginx
        state: started

    - name: ensure to copy and configure nginx
      copy: dest=/etc/nginx/sites-available/default
            src=./default

    - name: ensure to copy and configure php files
      copy: dest=/var/www/html/index.php
            src=./index.php

    - name: ensure nginx restart
      service:
        name: nginx
        state: restarted

- hosts: haproxy
  become: yes
  vars:
    Mymessage: "Welcome to haproxy loadbalancer"
    haproxy_mode: http
    haproxy_algorithm:  roundrobin
    haproxy_backend_servers: backend_servers

  tasks:
    - name: ensure to  Install HAProxy 
      apt: 
        name: haproxy 
        state:  present
    
    - name: ensure to copy HAProxy Configuration File 
      template:
        src:  haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg